server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Cache control for static assets to improve load performance (excluding JS)
    location ~* \.(?:css|jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc)$ {
        root /usr/share/nginx/html;
        expires 1M;
        access_log off;
        add_header Cache-Control "public";
    }

    # Don't cache index.html, JS files, or service worker to ensure updates are seen
    location ~* \.(?:manifest|appcache|html?|xml|json|js)$ {
        root /usr/share/nginx/html;
        expires -1;
        access_log off;
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
