name: Deploy to GitHub Pages

on:
  push:
    branches:
      - develop # Trigger deployment on pushes to the develop branch

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.x'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web --base-href "/Healix/"

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build/web
          branch: gh-pages # The branch the action will deploy to.
